### ISSUE TITLE
Keycloak Docs Update

### ISSUE THREAD

**Issue by stereo9** [kimai/www.kimai.org#106]
@ https://github.com/kimai/www.kimai.org/blob/master/_documentation/keycloak.md

One Setting to make Keycloak work with Kimai is missing:

***Adjust Client Scopes***
* Go to Configuration -> Client Scopes -> role_list
* Select Tab "Mappers", edit "role_list"
* Set" Single Role Attribute" to "ON"

**Comment by kevinpapst** [comment]
Thanks for sharing! 

Did you need to change anything in your Kimai config?

**Comment by stereo9** [comment]
> Thanks for sharing!
> 
> Did you need to change anything in your Kimai config?

Nope, the rest worked perfectly!

**Comment by kevinpapst** [comment]
Totally forgot to add this, finally did. Thanks @stereo9 👍
