### ISSUE TITLE
Add clear cache for translations to be displayed

### ISSUE THREAD

**Issue by GhostPengy** [kimai/www.kimai.org#115]
The translation guide does not state the need for the cache to be cleared. Without cache being cleared, translations do not show up. I was sitting and wondering why my language did not show up for a while.

`bin/console cache:clear`

**Comment by hebrides** [comment]
The site appeared like this Firefox today:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/7585440/155246251-6d6508df-b39f-4c78-afa0-4623359c4ccc.png">

**Comment by kevinpapst** [comment]
@GhostPengy added a hint about the cache, thanks for letting me know!

@hebrides interesting... but the website is static HTML, so this problem is likely some kind of firefox rendering font issue
