### ISSUE TITLE
iPhone 6 not working (was: Allow line break in header)

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#124]
**Problem**
When viewing the website with my iPhone 6 the header/titel **Kimai time-tracker** has an overlapping issue in Croatian.

- In Portrait mode, the "Cloud" icon can be accesses, but the Menu icon not!
![kimai-portrait](https://user-images.githubusercontent.com/43657314/155378412-684d91ea-df2f-4221-a9de-6d7cc9a306e4.jpg)

- In landscape mode, the language options overlapp the header text at certain widths!
![kimai-landscape](https://user-images.githubusercontent.com/43657314/155375612-8b5be6e2-780b-44ea-96e6-520d4563548f.jpg)

**Solution**
Redesign (do some CSS changes) `<div class="header py-4">`. For instance, allow text wrapping - currently you have `white-space: nowrap;` in the CSS `.header-brand`.

**Feature request**
Enable the website to recognize the user's/browser's locale settings. That way you would not need the _language-switch_ div at all (but you could keep the language options in the menu).

I'm not a programmer and don't really know how to do that without breaking other stuff. So I hope you can solve the issue yourself :-(

**Comment by kevinpapst** [comment]
Can you retest with the redesigned website elements?
The other languages currently allow to scale down to 300px, but croatian needs at least 360px.

I am not sure about usage of mobile phones and what the 90% ratio of minimum pixel size is.

It looks good here, but my phone is rather new and has a larger screen, so this might not be representative.
I have one idea, which I will work on now and get back to you later.

**Comment by kevinpapst** [comment]
Alright, that solution came quick... I hide everything behind "Kimai" now in the smallest grid size.

That allows to show the icons in every size screen. Thanks for posting the suggestion 👍 

Sorry it took so long, but step-by-steop it gets better 😄

**Comment by milotype** [comment]
@kevinpapst 
My feedback:

1. Enable automatic localized/translated versions of the website when searching "kimai.org" in a browser, depending upon the browsers or OS locale setting.
2. On my iPhone6 the "hamburger" icon on the left side and the "globe" (languages) icon don't work – when tapped, nothing happens. The "cloud" icon works.

**Comment by kevinpapst** [comment]
Hm, I just charged my iPhone 6s and it works with iOs 15.2.1 and Safari. 
Probably a caching issue?

**Comment by milotype** [comment]
@kevinpapst Hmm … My iPhone 6 has iOS 12.5.6.

- I've just deleted the history and webpage data in the Safari settings on my iPhone. The issue number 2 still remains.
- Also issue number 1 is still present.

**Comment by kevinpapst** [comment]
Yeah, the 6 was taken out of updates way earlier than the 6s. 

The website is based on Tabler => Bootstrap 5 => https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/

Can't find the Safari version on my iPhone, but it has the search bar at the bottom, so it must be a rather recent release I believe.

It's a pitty if it doesn't work, does https://preview.tabler.io/ work for you ?

**Comment by milotype** [comment]
@kevinpapst Yes, https://preview.tabler.io/ works on my computer and om my iPhone.

**Comment by kevinpapst** [comment]
Ok, then I will have to check if there is some javascript missing, that might be required for older phones.

Does the new "Version 2" demo work on your iphone? https://www.kimai.org/demo/

**Comment by milotype** [comment]
@kevinpapst No. It has the same problems. :-(

**Comment by kevinpapst** [comment]
How frustrating... as I have no chance to debug it. 
I'll check and if I find something, I will post an update and ask you for one more round of testing

**Comment by kevinpapst** [comment]
I just deployed a complete re-design of the website.

Not sure though how that looks on an iPhone 6. I hope it isn't broken...
