### ISSUE TITLE
Translation of webpage

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#127]
Enable translating the `h2`, `subtitles`, `tags` and the **FAQ** section on the webpage [Documentation](https://www.kimai.org/documentation/)

**Comment by kevinpapst** [comment]
I moved the FAQ to a dedicated page: https://www.kimai.org/documentation/faq-onpremise.html

Like all documentation pages, these are not translatable by now, but I will think of a way to enable that.
