### ISSUE TITLE
Missing main website menu on the Documentation page

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#146]
**Problem:**
When switching to the [Documentation](https://www.kimai.org/documentation/) webpage, there is no menu to change the language nor navigate to other webpages (Home, About Kimai, Demo, etc.). 

Depending upon the width of the screen (browsers window) there is only the menu for the _Documentation_ page

![Missing languages main menu and cloud](https://user-images.githubusercontent.com/43657314/187525991-9a09bf21-e881-4507-b6b0-300baaf2ff5c.png)

or the Cloud button and the menu for the _Documentation_ page itself

![Missing languages and main menu](https://user-images.githubusercontent.com/43657314/187526017-30ece9e4-a7c1-4437-9027-830ff704f4ba.png)

**What should happen:**
In both cases there should be a menu to change the language and to navigate to other webpages (Home, About Kimai, Demo, etc.) just as on the other webpages.

**Suggestion:**
- Add the main website menu in the _header_ of the _Documentation_ page, just like all other website pages have it, in order to enable navigation to other webpages.
- Add some sort of a submenu for the _Documentation_ page.
- Maybe you can implement some sort of grouping within the menu.

Maybe you can use the _fa-language_ icon or the _fa-globe_ icon (which you use for the https://www.kimai.cloud/ website) to select languages, just as you use the _fa-cloud_ icon of the **Font Awesome font**. When clicking the "language" icon, a dropdown menu should appear to select the language.

I would like to help you out with this issue, but I'm not a programmer :-(

**Comment by kevinpapst** [comment]
Hi Milo,

all of that is on purpose for now. 

1. Translations:
Documentation is not translated the URLs currently do not exist in multiple languages. This is a bigger refactoring issue that I will not tackle right now, but we will keep the issue open for later when I have the time and inspiration to work on that issue.

2. Menu:
If you are navigating the documentation is is very likely that you do not want to see anything else but the documentation => increased focus. Also every page in Kimai links to the documentation, so when someone visits the documentation, a link to e.g. the marketplace (especially when coming from the cloud) will be very irritating.
So I deliberately removed the main navigation from the docs.
Last but not least: too many pages to somehow squeeze them in only one submenu or way less user-friendly

3. Icon:
I already tried the dropdown approach in the past and will probably try to add it in the future with the next languages/translation of the website. For now it works pretty well in desktop and mobile. 

Anyway: I will work on 1 & 3 at some point and then I gill give you an update.

Thanks for your support and your input, I really really appreciate that, much more than words in a comment field can express  😊
