### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#153]
Enable tranlsation of the following strings. See screenshots.

![ License and purchase details ](https://user-images.githubusercontent.com/43657314/188467473-292ba21a-81fd-4113-9db1-17ea37e92205.png)

![ Pricing for this item ](https://user-images.githubusercontent.com/43657314/188467479-efe5952f-7abd-40c3-b5d6-ed9752932d09.png)

**Comment by kevinpapst** [comment]
I am aware that there are still a lot of missing translations ... let's take one step after another 😁 
You can update your environment, these strings and some other are now translatable.
