### ISSUE TITLE
Clear Cache Functionality

### ISSUE THREAD

**Issue by mbiolsi** [kimai/www.kimai.org#180]
Would it be possible to add a plugin that would allow us to clear cache from Kimai? When editing templates, it can take a lot of time to edit code, clear cache, edit code, clear cache.

**Comment by kevinpapst** [comment]
Switch to dev mode (read symfony docs or the kimai developer docs).
Basically that means installing composer packages without "no-dev" flag and then switching `APP_ENV=dev` in your .env file.

Dev mode will reload changed templates on any page reload.

Next time, please post here: https://github.com/kevinpapst/kimai2/discussions
