### ISSUE TITLE
php package php8.1-gd missing in installation documentation

### ISSUE THREAD

**Issue by iusgit** [kimai/www.kimai.org#191]
In file _documentation/fresh-ubuntu-20.md we have the line `apt install php8.1-fpm php8.1-cli php8.1-common php8.1-opcache php8.1-readline php8.1-xml php8.1-zip php8.1-intl php8.1-mbstring php8.1-mysql php8.1-curl`. 

During the installation procedure it is said that `php8.1-gd` is missing. It could be added to the line.

**Comment by kevinpapst** [comment]
That's a mixup with the upcoming 2.0. I re-added it and will review the packages for 2.0 later.

Thanks for sharing 👍
