### ISSUE TITLE
Add 'provider' key to SAML documentation

### ISSUE THREAD

**Issue by RichardJong** [kimai/www.kimai.org#222]
To get SAML working I needed to add `provider: Google` to my `local.yaml`.
This configuration step is missing in the [documentation](https://github.com/kimai/www.kimai.org/blob/770807a3464321bbd930182a4c800cb6ec764537/_documentation/saml.md).

**Comment by kevinpapst** [comment]
Thanks for your feedback  testing the beta version of Kimai!

I added the provider tag to the docs. Lets hope not too many people will now complain that it does not work, becuase there is a superficial config entry called "provider" 😁
