### ISSUE TITLE
instructions for add plugin to store

### ISSUE THREAD

**Issue by owlysk** [kimai/www.kimai.org#259]
Hi, I create app which I want to publish to your store, but I don't know how.
I follow instruction on https://www.kimai.org/documentation/store.html but after I made changes, what should I do next?

I'm sorry, but this is all new for me. Thanks

**Comment by kevinpapst** [comment]
You have to send a Pull Request with your changes (please allow edits from maintainer, so I can fix stuff).
I will check and tell you, if I need more infos.

I just checked the widget and di not understand how to use it. It is meant for a specific platform?

**Comment by owlysk** [comment]
Hi, thanks for response. Pull request sent :)

To your question, it's desktop app. You need to unzip release and then you run specific executable for you system. Runs on Windows, Linux and Mac OS. Then app window shows,  you need to go to the setting and setup credentials to your Kimai sever.
It's small widget app like Clockify, where you can start/stop/repeat timesheets.

**Comment by kevinpapst** [comment]
Thanks 👍 I need a bit to add it, will get back to you in a few days.

**Comment by owlysk** [comment]
Ok, thank you
