### ISSUE TITLE
Outdated doku of plugin development

### ISSUE THREAD

**Issue by PascalHoenisch** [kimai/www.kimai.org#275]
### The [documentation](https://github.com/kimai/www.kimai.org/blob/main/_documentation/plugins.md) seems to be outdated for Kimai2.

E.g. the doku states that a composer.json file with the following part should be created and no string for v2 of kimai.
`"extra": {
        "kimai": {
            "require": "1.3",
            "name": "YourBundle"
        }
    }`
However for `require` the number 2000 should be used as further explained.

Trying to create a plugin with this guide failed for me. I only managed to create one while reconstructing from the [DemoBundle](https://github.com/Keleo/DemoBundle). For me this means the guide is partly outdated.

**Comment by kevinpapst** [comment]
Yes, that is correct, thanks for creating the issue.

If anyone wants to help improve the docs, PRs are welcome 👍

**Comment by kevinpapst** [comment]
Fixed the composer part and added info about `FileHelper`
