### ISSUE TITLE
SmallBusinessRuleBundle now compatible for Kimai v2.0

### ISSUE THREAD

**Issue by LiaraAlis** [kimai/www.kimai.org#277]
The store shows the SmallBusinessRule as not compatible for Kimai 2.0: https://www.kimai.org/store/liaraalis-small-business-rule-bundle.html

But now, v2.0 of the bundle has been released:
https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/releases/tag/v2.0.0

Are there any steps needed to update the store page?

**Comment by kevinpapst** [comment]
Add a new line with the compatible version  e.g. `[ "2.0", "2.0.20" ]` (first = yours, 2 = Kimai). 
The site will then remove the warning.

https://github.com/kimai/www.kimai.org/blob/main/_data/store/liaraalis-small-business-rule-bundle.yml#L12

**Comment by LiaraAlis** [comment]
Thanks. The most obvious was once again invisible. :D
Created PR: #279

**Comment by kevinpapst** [comment]
Thanks for the update @LiaraAlis
