### ISSUE TITLE
Missing information for custom fonts in invoices 

### ISSUE THREAD

**Issue by lukasassmann** [kimai/www.kimai.org#280]
It should be added to the invoice documentation (https://www.kimai.org/documentation/invoices.html) that keys for custom fonts in documents need to be lowercase.

mPDF states this in their docs: https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html in the example code it says "lowercase letters only in font key".

Took me quite a while to find that since i was trying to add a font using an uppercase key

**Comment by kevinpapst** [comment]
Aha, never heard of that one.
Thanks for finding and sharing 👍 
That explains my troubles in the past as well.
I will update the docs and probably apply a fix to Kimai, so all keys are lowercased by default.

**Comment by kevinpapst** [comment]
Will be fixed with https://github.com/kimai/kimai/pull/4178 - so we do not need these additional docs

**Comment by lukasassmann** [comment]
I would argue it’s a good idea to mention it in the docs anyway, stating that with version 2.0.29 keys will be auto-lowercased. 

This will spare people with a version < 2.0.29 the frustration
