### ISSUE TITLE
Cloud registration: `ERROR: This value is already in use` persists after first entry

### ISSUE THREAD

**Issue by mark-pitblado** [kimai/www.kimai.org#351]
When signing up for kimai cloud, the website asks the user to pick a name for their cloud, which gets created as a subdomain on the kimai.cloud domain. As such, each user must select a unique name.

After the first entry, the `ERROR: This value is already in use` will stay active, even after the text box is cleared. Future entries (that are unique), will not clear the error. 

The user can bypass this bug by selecting the checkbox and agreeing to the terms and conditions then clicking save, however as the save button is greyed out, this isn't obvious and could be improved by having the error message disappear and the button return to its active clickable state after the text field is cleared from the original entry, or when a new unique cloud name is successfully entered.

**Comment by kevinpapst** [comment]
Thanks for your feedback 👍  

I agree, the entire onboarding flow needs a refresh.
