### ISSUE TITLE
remove ugly stolen AI junk from your landing page

### ISSUE THREAD

**Issue by mrshmllow** [kimai/www.kimai.org#372]
Is this really how you wanna sell your project? Lazy, stolen images? They look horrible and completely clash with your green branding. You couldnt even be bothered to properly photoshop the messed up looking text. They all have 0 cohesion, each with completely different backgrounds and colours.

**Comment by kevinpapst** [comment]
You are implying copyright infringement, which causes critical reputation damage.
I had fun creating these AI images. Nothing is stolen. This is a complete lie.

I can only imagine what prompted you to post this embarrassing stuff, and even if your content might have some tiny truth in it (talking colors), you should understand that not everyone has the abilities for image manipulation. And I don't know why I should ever touch Photoshop, that company is using the darkest patterns in software selling that I know of. I wouldn't use their software even if it was a gift. 

I'll quote myself, as you seem to have missed it:

> There is one simple rule in our "Code of conduct": Don't be an ass!

You are a stranger to me and I have no idea why you come here in this tone. I don't have the resources to take care of such toxic comments, so I will block you now. 

Good luck and learning how to talk respectful to people, online and offline!
