### ISSUE TITLE
[Docs] Lockdown period documentation seems not to align with implementation code

### ISSUE THREAD

**Issue by sharky98** [kimai/www.kimai.org#376]
When looking through the docs for the translation, I was wondering how the lockdown period worked. The docs seems to not be aligned with how [src/Timesheet/LockdownService.php](https://github.com/kimai/kimai/blob/12ef19df28fd9bf2bf4a849664bea681c2fe55fd/src/Timesheet/LockdownService.php) is working in few points.

## Relative to now

It seems that the lockdown period are not checked against now for neither [start][code-start] or [end][code-end], but are used (almost) as-is to create a new `DateTimeImmutable`.

While I understand that PHP will check the relative string to now with string like `-2 weeks`, it won't do it if provided a more "*fixed*" relative string such as `last day of next month`[^1].

[^1]: OK, it still uses `now` to be relative to. However this is not within an arithmetic calculation. And the user could provide a fixed month and year such as `last sat of July 2008` (but why?!).

I would suggest removing reference to `relative to now` in the docs (and translations to [start][translations-start], [end][translations-end]) to avoid confusion.

## Grace Relative to lockdown end period

Here, the [docs][docs-grace] seems to tell us that the relative date string will be used against the end of the lockdown period, but could be modified with the `of` modifier. However this seems partly true when looking at the [code][code-grace]. It seems that the grace period is used to modify the lockdown end period. So, if I understand the code correctly, if the grace period is `+2 weeks`, it works as expected (2 weeks after the lockdown end period). However, if the grace period is `last day of next month` and this is applied on the lockdown end period, this would mean that the grace period would be extended more than expected[^2].

[^2]: Like if the lockdown is set to `last day of next month` and grace to `last day of next month`, relative to today (2024-01-26), the lockdown will end on 2024-02-29 but the grace period will be set to 2024-03-31, while the docs seems to tell us that using `of` will bring it to relative to today.

## Activating the lockdown

The [docs][docs-activating] tell us the lockdown will be active if all three fields are populated. But the [code][code-activating] seems to check only for start and end, not grace.

[code-activating]: https://github.com/kimai/kimai/blob/12ef19df28fd9bf2bf4a849664bea681c2fe55fd/src/Timesheet/LockdownService.php#L24-L31
[docs-activating]: https://github.com/kimai/www.kimai.org/blob/c18e8d6e8ac9bc4a48698ea12bfcbfe365d60343/_documentation/configurations.md?plain=1#L69
[docs-grace]: https://github.com/kimai/www.kimai.org/blob/c18e8d6e8ac9bc4a48698ea12bfcbfe365d60343/_documentation/configurations.md?plain=1#L64
[code-start]: https://github.com/kimai/kimai/blob/12ef19df28fd9bf2bf4a849664bea681c2fe55fd/src/Timesheet/LockdownService.php#L55-L65
[code-end]: https://github.com/kimai/kimai/blob/12ef19df28fd9bf2bf4a849664bea681c2fe55fd/src/Timesheet/LockdownService.php#L98-L108
[code-grace]: https://github.com/kimai/kimai/blob/12ef19df28fd9bf2bf4a849664bea681c2fe55fd/src/Timesheet/LockdownService.php#L141-L156
[translations-start]: https://hosted.weblate.org/translate/kimai/system-configuration/fr/?checksum=2244fa0a3390ee27
[translations-end]: https://hosted.weblate.org/translate/kimai/system-configuration/fr/?checksum=81d52d8602fa2ab9
[translations-grace]: https://hosted.weblate.org/translate/kimai/system-configuration/fr/?checksum=e5cc062f2e2cf0d1

**Comment by kevinpapst** [comment]
PHP relative datetimes are tricky especially the `of` modifier. Unfortunately I do not see a better solution then the one that is currently in place.
Which is successfully used by many companies.
