### ISSUE TITLE
Bug in the "Features" webpage

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#380]
Please check and repair the ["Features"](https://www.kimai.org/en/features.html) webpage.

The section with the "What can Kimai do for you?" contents appears twice before the section with headers "The best time-tracking features for you" and "Tech & Business Support".

This happens in other languages too!

**Comment by kevinpapst** [comment]
Ups, there was a broken template 😢 

Thank you for posting, fixed it!
