### ISSUE TITLE
Enable text wraping for narrow windows/screens

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#381]
Please check the problem at https://www.kimai.org/hr/.
Take look at the screenshots and change the CSS so text can wrap at narrow windows/screens.
The problem exist not just for the Croatian translation.

- **435 px screen width**
![CSS ul nowrap 435 px screen width](https://github.com/kimai/www.kimai.org/assets/43657314/23d3289f-423c-493b-9e0b-bc94c0eab3f4)

- **756 px screen width**
![CSS ul nowrap 756 px screen width](https://github.com/kimai/www.kimai.org/assets/43657314/ced02ae0-71df-4d0c-ab95-dfe7118f2c0e)

**Comment by kevinpapst** [comment]
Thank you 👍
