### ISSUE TITLE
Text alignement in the footer

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#382]
Please check the problem at https://www.kimai.org/hr/.
Take look at the screenshots and change/correct the CSS for text alignement for narrow windows/screens.
The problem exist not just for the Croatian translation.

- **435 px screen width**
![CSS ul footer 435 px screen width](https://github.com/kimai/www.kimai.org/assets/43657314/1298fb65-3aef-4a63-9065-dd0f3e50182c)

- **756 px screen width**
![CSS ul footer 756 px screen width](https://github.com/kimai/www.kimai.org/assets/43657314/a7eb262f-e2ae-4a15-afed-15933baed85b)

**Comment by kevinpapst** [comment]
There will always be some specific width where a responsive Layout doesn't look perfect. 
I fixed the first issue, the second one ... I'll keep it for later 😁  is 756px width screen something used often?
My stats say that around 80% of all visitors are on desktop anyway.

But: thanks for spotting these details, I appreciate your input!!!!!! ❤️

**Comment by milotype** [comment]
@kevinpapst Your welcome!

I'm not a programmer, so the issues I send are simply my observations … I don't think that 756px width screen is used often. On the other hand, IMO, the display of webpages should generally show in a correct manner, no matter of the screen size. But sticking to standards might be good :-)

Some references about screen sizes and breakpoints: 
https://www.altamira.ai/blog/common-screen-sizes-for-responsive-web-design/
https://learn.microsoft.com/en-us/windows/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design
https://en.wikipedia.org/wiki/Computer_display_standard

Cheers,
Milo
