### ISSUE TITLE
Add standard / default values

### ISSUE THREAD

**Issue by mifigap** [kimai/www.kimai.org#42]
Kevin, awesome product, it´s possible to add standard / default values (project and activity) to a customer?
When pressing on start at time tracking?
Also as an additional plugin in the shop.
Description:
Finish:
1. Start timetrack,
default is XY project
and
default is XY activity

Actually:
1. Start timetrack
2. Set project
3. Set activity

**Comment by toxiclung** [comment]
hello how did you solve this?

I also need to set default project and activity for users
