### ISSUE TITLE
Typo in landing first sentence

### ISSUE THREAD

**Issue by littletuna4** [kimai/www.kimai.org#467]
I'm not sure if this is a welcome issue haha but...

English site has a typo on the very first sentence.

Our open-source platform is designed to keep track of and analyze your **~~companies~~ company's** time-data, making it perfect for businesses of all sizes. Kimai helps you keep an eye on time and money.

**Comment by kevinpapst** [comment]
Thanks Tony 👍 Sure its welcome.
I am not a native speaker, which you can obviously see when reading the page 🤷 
I fixed the typo, should be online in about 15 minutes.

BTW Kimai and its website is translated at https://hosted.weblate.org/projects/kimai/
