### ISSUE TITLE
Custom shop link possible?

### ISSUE THREAD

**Issue by peat85** [kimai/www.kimai.org#476]
Hey Kevin,

we are going to re-release our Recurring Budget Plugin for v2 soon. We don't want to use third party shops (like Gumroad) for purchasing and distribution, but our own online shop.

Is it possible to provide our own custom URL for the "Buy Now" button in the Plugin store?

If so, what field would this be in the `.yml` file? Or should we just use the `gumroad` field regardless?

Thanks!

**Comment by kevinpapst** [comment]
I guess a new key needs to be added and the URL building logic needs to be added to:
- https://github.com/kimai/www.kimai.org/blob/main/_layouts/store-item.html
- https://github.com/kimai/www.kimai.org/blob/main/plugins.json

**Comment by kevinpapst** [comment]
now possible
