### ISSUE TITLE
email

### ISSUE THREAD

**Issue by heikomaier** [kimai/www.kimai.org#515]
Hello, I pulled Docker images [kimai/kimai2:apache &  mysql:8.3] and via docker compose everything works fine.
But email?
Following the kimai docs i could run
./bin/console **mailer:test** a@b.de --from=kimai@b.de    successfully!
 (there is only mailer:test and not mailer )

_You can test your email configuration by registering a new account or using the password reset function._
These 2 "things" don't work. MAILER_URL,MAILER_FROM and MAILER_DSN were set correctly.
 
So, may you help me about what's going wrong...
k.r. Heiko

**Comment by kevinpapst** [comment]
This is the right place to post your question:
https://github.com/kimai/kimai/discussions

**Comment by heikomaier** [comment]
Sry, my fault, going to git!
